spring:
    application:
        name: enterpriceapp
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy                
server:
    session:
        cookie:
            server.servlet.session.cookie.http-only: true

info:
    project:
        version: #project.version#                
                     
application: